import type { ApiProduct } from "./api/type"

const img = (url: string) => ({ public_id: url.split("/").pop() || "", secure_url: url })

export const MOCK_PRODUCTS: ApiProduct[] = [
  {
    _id: "baladi-bread",
    title: "Baladi Bread",
    description: "Stone-baked Egyptian flatbread, warm every hour",
    longDescription: "Our traditional Baladi Bread is stone-baked at extremely high temperatures to create the perfect pocket. Made with 100% whole wheat flour, water, yeast, and a touch of salt. Baked fresh hourly to ensure you receive it warm, soft, and aromatic.",
    price: 15,
    discountedPrice: 0,
    rating: 4.9,
    reviewsCount: 148,
    isBestseller: true,
    isAvailable: true,
    image: img("https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80"),
    category: { _id: "bread", name: "Bread", description: "", image: img(""), isDeleted: false, createdAt: "", updatedAt: "" },
    freshnessWindow: 6,
    tags: ["Daily Fresh", "Stone-baked", "Bestseller"],
    isDeleted: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "butter-croissant",
    title: "Butter Croissant Box",
    description: "6 pieces, 81 laminated layers each",
    longDescription: "Laminated with 48 layers of Normandy AOC butter (or 81 layers for maximum puffiness!). Shatteringly crisp on the outside, pillowy honeycomb within. Each batch takes 18 hours of careful lamination and temperature control before baking to golden perfection.",
    price: 150,
    discountedPrice: 0,
    rating: 4.9,
    reviewsCount: 387,
    isBestseller: true,
    isAvailable: true,
    image: img("https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80"),
    category: { _id: "pastry", name: "Pastry", description: "", image: img(""), isDeleted: false, createdAt: "", updatedAt: "" },
    freshnessWindow: 12,
    tags: ["Daily Fresh", "Laminated", "Bestseller"],
    isDeleted: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "feteer-meshaltet",
    title: "Feteer Meshaltet",
    description: "27 hand-stretched layers with honey & cream",
    longDescription: "A legendary Egyptian pastry, made of 27 paper-thin layers of hand-stretched dough layered with premium local ghee. Served warm with a side of pure clover honey and fresh country cream (eshta).",
    price: 85,
    discountedPrice: 0,
    rating: 5.0,
    reviewsCount: 219,
    isBestseller: true,
    isAvailable: true,
    image: img("https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=800&q=80"),
    category: { _id: "pastry", name: "Pastry", description: "", image: img(""), isDeleted: false, createdAt: "", updatedAt: "" },
    freshnessWindow: 8,
    tags: ["Daily Fresh", "Traditional", "Bestseller"],
    isDeleted: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "sourdough-loaf",
    title: "Artisanal Sourdough Loaf",
    description: "Naturally leavened sourdough bread",
    longDescription: "Baked with a 5-year-old active wild yeast starter. Features a thick, caramelized crust and an open, chewy crumb with a mild lactic tang. Fermented for 36 hours for optimal digestibility.",
    price: 95,
    discountedPrice: 0,
    rating: 4.8,
    reviewsCount: 92,
    isBestseller: false,
    isAvailable: true,
    image: img("https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80"),
    category: { _id: "bread", name: "Bread", description: "", image: img(""), isDeleted: false, createdAt: "", updatedAt: "" },
    freshnessWindow: 24,
    tags: ["Sourdough", "Artisanal"],
    isDeleted: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "kahk-cookies",
    title: "Kahk Eid Cookies Box",
    description: "Shortbread cookies dusted with powdered sugar",
    longDescription: "Rich shortbread cookies flavored with traditional 'Kahk essence' (rehet el kahk), stuffed with sweet honey-nut paste (agameya) or dates, and heavily dusted with powdered sugar. A festive Egyptian delicacy.",
    price: 180,
    discountedPrice: 0,
    rating: 4.7,
    reviewsCount: 64,
    isBestseller: false,
    isAvailable: true,
    image: img("https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&w=800&q=80"),
    category: { _id: "cookies", name: "Cookies", description: "", image: img(""), isDeleted: false, createdAt: "", updatedAt: "" },
    freshnessWindow: 120,
    tags: ["Festive", "Sweet"],
    isDeleted: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "basbousa-tray",
    title: "Semolina Basbousa Tray",
    description: "Sweet semolina cake soaked in syrup",
    longDescription: "Traditional Egyptian Basbousa made with fine semolina, yogurt, and coconut, baked until golden, soaked in warm rosewater syrup, and topped with whole almonds. Moist, soft, and perfectly sweet.",
    price: 110,
    discountedPrice: 0,
    rating: 4.9,
    reviewsCount: 115,
    isBestseller: false,
    isAvailable: false,
    image: img("https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80"),
    category: { _id: "desserts", name: "Desserts", description: "", image: img(""), isDeleted: false, createdAt: "", updatedAt: "" },
    freshnessWindow: 48,
    tags: ["Traditional", "Sweet", "Out of Stock"],
    isDeleted: false,
    createdAt: "",
    updatedAt: "",
  },
]

export const ALL_CATEGORIES = ["Bread", "Pastry", "Cookies", "Desserts"]
export const ALL_TAGS = ["Daily Fresh", "Stone-baked", "Laminated", "Traditional", "Sourdough", "Festive", "Sweet"]
